"""empty message

Revision ID: 0394b2015d49
Revises: 6e99102982ea
Create Date: 2022-01-30 20:19:21.204155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0394b2015d49'
down_revision = '6e99102982ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=True),
    sa.Column('notificado_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['notificado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacao_data_criacao'), 'notificacao', ['data_criacao'], unique=False)
    op.create_table('seguir',
    sa.Column('seguidor_id', sa.Integer(), nullable=False),
    sa.Column('seguido_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seguido_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['seguidor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('seguidor_id', 'seguido_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguir')
    op.drop_index(op.f('ix_notificacao_data_criacao'), table_name='notificacao')
    op.drop_table('notificacao')
    # ### end Alembic commands ###
