"""empty message

Revision ID: 11c95b74f8d4
Revises: 7eb6a851e0cf
Create Date: 2022-01-22 00:04:49.874569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c95b74f8d4'
down_revision = '7eb6a851e0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emblemas', sa.Column('nome_imagem', sa.String(length=100), nullable=True))
    op.drop_column('emblemas', 'nome_foto')
    op.add_column('licoes_amei', sa.Column('licao_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'licoes_amei', type_='foreignkey')
    op.create_foreign_key(None, 'licoes_amei', 'licoes', ['licao_id'], ['id'])
    op.drop_column('licoes_amei', 'licoe_id')
    op.add_column('materias', sa.Column('nome_simples', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'materias', ['nome_simples'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materias', type_='unique')
    op.drop_column('materias', 'nome_simples')
    op.add_column('licoes_amei', sa.Column('licoe_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'licoes_amei', type_='foreignkey')
    op.create_foreign_key(None, 'licoes_amei', 'licoes', ['licoe_id'], ['id'])
    op.drop_column('licoes_amei', 'licao_id')
    op.add_column('emblemas', sa.Column('nome_foto', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('emblemas', 'nome_imagem')
    # ### end Alembic commands ###
