"""empty message

Revision ID: 308d363bd852
Revises: e0e608d5571e
Create Date: 2021-12-05 06:06:38.075962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308d363bd852'
down_revision = 'e0e608d5571e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=16), nullable=True),
    sa.Column('materia', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('conteudo', sa.String(length=2000), nullable=True),
    sa.Column('opcaoa', sa.String(length=2000), nullable=True),
    sa.Column('opcaob', sa.String(length=2000), nullable=True),
    sa.Column('opcaoc', sa.String(length=2000), nullable=True),
    sa.Column('opcaod', sa.String(length=2000), nullable=True),
    sa.Column('opcaoe', sa.String(length=2000), nullable=True),
    sa.Column('explicacao', sa.String(), nullable=True),
    sa.Column('explicacao_markdown', sa.String(), nullable=True),
    sa.Column('explicacao_html', sa.String(), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('prova', sa.String(length=10), nullable=True),
    sa.Column('dia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materia'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('subtitulo', sa.String(length=100), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('conteudo_html', sa.Text(), nullable=True),
    sa.Column('nome_foto', sa.String(length=100), nullable=True),
    sa.Column('n_palavras', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licoes_data'), 'licoes', ['data'], unique=False)
    op.create_table('questoes_topicos',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'questao_id')
    )
    op.create_table('licoes_amei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('licoe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['licoe_id'], ['licoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licoes_topicos',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('licao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['licao_id'], ['licoes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'licao_id')
    )
    op.add_column('comentarios', sa.Column('licao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comentarios', 'licoes', ['licao_id'], ['id'])
    op.add_column('tags', sa.Column('materia', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'materias', ['materia'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'materia')
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.drop_column('comentarios', 'licao_id')
    op.drop_table('licoes_topicos')
    op.drop_table('licoes_amei')
    op.drop_table('questoes_topicos')
    op.drop_index(op.f('ix_licoes_data'), table_name='licoes')
    op.drop_table('licoes')
    op.drop_table('questoes')
    op.drop_table('materias')
    # ### end Alembic commands ###
