"""empty message

Revision ID: 3e7533747c82
Revises: e19d91a49e71
Create Date: 2021-12-03 23:05:15.800728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7533747c82'
down_revision = 'e19d91a49e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('facebook', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('instagram', sa.String(length=30), nullable=True))
    op.add_column('usuarios', sa.Column('twitter', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'twitter')
    op.drop_column('usuarios', 'instagram')
    op.drop_column('usuarios', 'facebook')
    # ### end Alembic commands ###
