"""empty message

Revision ID: 5617d00232eb
Revises: 92aa4bc407e8
Create Date: 2021-12-05 20:43:42.447320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5617d00232eb'
down_revision = '92aa4bc407e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topicos_amei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('topico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes_amei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('questao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios_amei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('comentario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comentario_id'], ['comentarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios_amei')
    op.drop_table('questoes_amei')
    op.drop_table('topicos_amei')
    # ### end Alembic commands ###
