"""empty message

Revision ID: 56cdbc02936c
Revises: 8a553f1480e5
Create Date: 2020-10-13 16:02:02.405828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cdbc02936c'
down_revision = '8a553f1480e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=64), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('idioma', sa.String(length=8), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicacoes_data'), 'publicacoes', ['data'], unique=False)
    op.create_table('publicacoes_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('publicacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacoes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'publicacao_id')
    )
    op.add_column('usuarios', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'avatar_hash')
    op.drop_table('publicacoes_tags')
    op.drop_index(op.f('ix_publicacoes_data'), table_name='publicacoes')
    op.drop_table('publicacoes')
    op.drop_table('tags')
    # ### end Alembic commands ###
