"""empty message

Revision ID: 587038354a14
Revises: 56cdbc02936c
Create Date: 2020-10-15 17:59:41.868436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587038354a14'
down_revision = '56cdbc02936c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publicacoes', 'conteudo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('publicacoes', 'titulo',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publicacoes', 'titulo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('publicacoes', 'conteudo',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
