"""empty message

Revision ID: 5db635889b59
Revises: 68db21689d1d
Create Date: 2021-02-21 10:56:34.018279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db635889b59'
down_revision = '68db21689d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscricoes_feu_rosa', sa.Column('horario', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inscricoes_feu_rosa', 'horario')
    # ### end Alembic commands ###
