"""empty message

Revision ID: 63f6aaac7980
Revises: 0394b2015d49
Create Date: 2022-02-03 12:49:54.894750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f6aaac7980'
down_revision = '0394b2015d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicacoes', sa.Column('conteudo_truncado', sa.String(length=210), nullable=True))
    op.add_column('seguir', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.add_column('seguir', sa.Column('seguido_id', sa.Integer(), nullable=False))
    op.add_column('seguir', sa.Column('seguidor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'seguir', 'usuarios', ['seguidor_id'], ['id'])
    op.create_foreign_key(None, 'seguir', 'usuarios', ['seguido_id'], ['id'])
    op.drop_column('seguir', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seguir', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'seguir', type_='foreignkey')
    op.drop_constraint(None, 'seguir', type_='foreignkey')
    op.drop_column('seguir', 'seguidor_id')
    op.drop_column('seguir', 'seguido_id')
    op.drop_column('seguir', 'data_criacao')
    op.drop_column('publicacoes', 'conteudo_truncado')
    # ### end Alembic commands ###
