"""empty message

Revision ID: 69de54181473
Revises: 1d96f0005fa7
Create Date: 2021-11-29 10:11:21.439588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69de54181473'
down_revision = '1d96f0005fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicacoes', sa.Column('n_palavras', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicacoes', 'n_palavras')
    # ### end Alembic commands ###
