"""empty message

Revision ID: 6e99102982ea
Revises: ee7394dfec9a
Create Date: 2022-01-30 10:17:34.786662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e99102982ea'
down_revision = 'ee7394dfec9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=True),
    sa.Column('notificado_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['notificado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacao_data_criacao'), 'notificacao', ['data_criacao'], unique=False)
    op.add_column('comentarios', sa.Column('curso_id', sa.Integer(), nullable=True))
    op.add_column('comentarios', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comentarios_data_criacao'), 'comentarios', ['data_criacao'], unique=False)
    op.drop_index('ix_comentarios_data', table_name='comentarios')
    op.create_foreign_key(None, 'comentarios', 'cursos', ['curso_id'], ['id'])
    op.drop_column('comentarios', 'data')
    op.add_column('cursos', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.add_column('cursos', sa.Column('descricao', sa.String(length=400), nullable=True))
    op.add_column('cursos', sa.Column('instrutor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cursos_data_criacao'), 'cursos', ['data_criacao'], unique=False)
    op.create_foreign_key(None, 'cursos', 'usuarios', ['instrutor_id'], ['id'])
    op.add_column('emblemas', sa.Column('data_criacao', sa.Date(), nullable=True))
    op.add_column('emblemas', sa.Column('nome_imagem', sa.String(length=100), nullable=True))
    op.drop_column('emblemas', 'nome_foto')
    op.drop_column('emblemas', 'data')
    op.add_column('licoes', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_licoes_data_criacao'), 'licoes', ['data_criacao'], unique=False)
    op.drop_index('ix_licoes_data', table_name='licoes')
    op.drop_column('licoes', 'data')
    op.add_column('licoes_amei', sa.Column('licao_id', sa.Integer(), nullable=True))
    op.drop_constraint('licoes_amei_licoe_id_fkey', 'licoes_amei', type_='foreignkey')
    op.create_foreign_key(None, 'licoes_amei', 'licoes', ['licao_id'], ['id'])
    op.drop_column('licoes_amei', 'licoe_id')
    op.add_column('materias', sa.Column('emoji', sa.String(length=1), nullable=True))
    op.add_column('materias', sa.Column('nome_simples', sa.String(length=32), nullable=True))
    op.add_column('materias', sa.Column('tipo', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'materias', ['nome_simples'])
    op.add_column('publicacoes', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_publicacoes_data_criacao'), 'publicacoes', ['data_criacao'], unique=False)
    op.drop_index('ix_publicacoes_data', table_name='publicacoes')
    op.drop_column('publicacoes', 'data')
    op.add_column('questoes', sa.Column('enem', sa.Boolean(), nullable=True))
    op.add_column('questoes', sa.Column('licao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questoes', 'licoes', ['licao_id'], ['id'])
    op.add_column('topicos', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.add_column('topicos', sa.Column('descricao', sa.String(length=400), nullable=True))
    op.add_column('topicos', sa.Column('titulo', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_topicos_data_criacao'), 'topicos', ['data_criacao'], unique=False)
    op.drop_column('topicos', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topicos', sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_topicos_data_criacao'), table_name='topicos')
    op.drop_column('topicos', 'titulo')
    op.drop_column('topicos', 'descricao')
    op.drop_column('topicos', 'data_criacao')
    op.drop_constraint(None, 'questoes', type_='foreignkey')
    op.drop_column('questoes', 'licao_id')
    op.drop_column('questoes', 'enem')
    op.add_column('publicacoes', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_publicacoes_data', 'publicacoes', ['data'], unique=False)
    op.drop_index(op.f('ix_publicacoes_data_criacao'), table_name='publicacoes')
    op.drop_column('publicacoes', 'data_criacao')
    op.drop_constraint(None, 'materias', type_='unique')
    op.drop_column('materias', 'tipo')
    op.drop_column('materias', 'nome_simples')
    op.drop_column('materias', 'emoji')
    op.add_column('licoes_amei', sa.Column('licoe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'licoes_amei', type_='foreignkey')
    op.create_foreign_key('licoes_amei_licoe_id_fkey', 'licoes_amei', 'licoes', ['licoe_id'], ['id'])
    op.drop_column('licoes_amei', 'licao_id')
    op.add_column('licoes', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_licoes_data', 'licoes', ['data'], unique=False)
    op.drop_index(op.f('ix_licoes_data_criacao'), table_name='licoes')
    op.drop_column('licoes', 'data_criacao')
    op.add_column('emblemas', sa.Column('data', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('emblemas', sa.Column('nome_foto', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('emblemas', 'nome_imagem')
    op.drop_column('emblemas', 'data_criacao')
    op.drop_constraint(None, 'cursos', type_='foreignkey')
    op.drop_index(op.f('ix_cursos_data_criacao'), table_name='cursos')
    op.drop_column('cursos', 'instrutor_id')
    op.drop_column('cursos', 'descricao')
    op.drop_column('cursos', 'data_criacao')
    op.add_column('comentarios', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.create_index('ix_comentarios_data', 'comentarios', ['data'], unique=False)
    op.drop_index(op.f('ix_comentarios_data_criacao'), table_name='comentarios')
    op.drop_column('comentarios', 'data_criacao')
    op.drop_column('comentarios', 'curso_id')
    op.drop_index(op.f('ix_notificacao_data_criacao'), table_name='notificacao')
    op.drop_table('notificacao')
    # ### end Alembic commands ###
