"""empty message

Revision ID: 744525165bb4
Revises: 93d1f6108a8b
Create Date: 2020-10-09 07:36:06.927896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744525165bb4'
down_revision = '93d1f6108a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('padrao', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissoes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_padrao'), 'roles', ['padrao'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_padrao'), table_name='roles')
    op.drop_column('roles', 'permissoes')
    op.drop_column('roles', 'padrao')
    # ### end Alembic commands ###
