"""empty message

Revision ID: 7eb6a851e0cf
Revises: 458d35aca468
Create Date: 2021-12-05 21:24:44.003770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb6a851e0cf'
down_revision = '458d35aca468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentarios', sa.Column('questao_id', sa.Integer(), nullable=True))
    op.add_column('comentarios', sa.Column('topico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comentarios', 'topicos', ['topico_id'], ['id'])
    op.create_foreign_key(None, 'comentarios', 'questoes', ['questao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.drop_column('comentarios', 'topico_id')
    op.drop_column('comentarios', 'questao_id')
    # ### end Alembic commands ###
