"""empty message

Revision ID: 885892d38d1f
Revises: 308d363bd852
Create Date: 2021-12-05 19:51:04.636363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885892d38d1f'
down_revision = '308d363bd852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('nome_foto', sa.String(length=100), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('nome_foto', sa.String(length=100), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('licoes', sa.Column('curso_id', sa.Integer(), nullable=True))
    op.add_column('licoes', sa.Column('topico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'licoes', 'cursos', ['curso_id'], ['id'])
    op.create_foreign_key(None, 'licoes', 'topicos', ['topico_id'], ['id'])
    op.add_column('materias', sa.Column('nome_foto', sa.String(length=100), nullable=True))
    op.add_column('questoes', sa.Column('autor_id', sa.Integer(), nullable=True))
    op.add_column('questoes', sa.Column('curso_id', sa.Integer(), nullable=True))
    op.add_column('questoes', sa.Column('materia_id', sa.Integer(), nullable=True))
    op.add_column('questoes', sa.Column('topico_id', sa.Integer(), nullable=True))
    op.drop_constraint('questoes_materia_fkey', 'questoes', type_='foreignkey')
    op.create_foreign_key(None, 'questoes', 'materias', ['materia_id'], ['id'])
    op.create_foreign_key(None, 'questoes', 'usuarios', ['autor_id'], ['id'])
    op.create_foreign_key(None, 'questoes', 'topicos', ['topico_id'], ['id'])
    op.create_foreign_key(None, 'questoes', 'cursos', ['curso_id'], ['id'])
    op.drop_column('questoes', 'explicacao_markdown')
    op.drop_column('questoes', 'materia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questoes', sa.Column('materia', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questoes', sa.Column('explicacao_markdown', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questoes', type_='foreignkey')
    op.drop_constraint(None, 'questoes', type_='foreignkey')
    op.drop_constraint(None, 'questoes', type_='foreignkey')
    op.drop_constraint(None, 'questoes', type_='foreignkey')
    op.create_foreign_key('questoes_materia_fkey', 'questoes', 'materias', ['materia'], ['id'])
    op.drop_column('questoes', 'topico_id')
    op.drop_column('questoes', 'materia_id')
    op.drop_column('questoes', 'curso_id')
    op.drop_column('questoes', 'autor_id')
    op.drop_column('materias', 'nome_foto')
    op.drop_constraint(None, 'licoes', type_='foreignkey')
    op.drop_constraint(None, 'licoes', type_='foreignkey')
    op.drop_column('licoes', 'topico_id')
    op.drop_column('licoes', 'curso_id')
    op.drop_table('topicos')
    op.drop_table('cursos')
    # ### end Alembic commands ###
