"""empty message

Revision ID: 8a553f1480e5
Revises: 744525165bb4
Create Date: 2020-10-10 05:36:16.591456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a553f1480e5'
down_revision = '744525165bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('localizacao', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('membro_desde', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('nome', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('sobre', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('sobrenome', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('ultimo_acesso', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ultimo_acesso')
    op.drop_column('usuarios', 'sobrenome')
    op.drop_column('usuarios', 'sobre')
    op.drop_column('usuarios', 'nome')
    op.drop_column('usuarios', 'membro_desde')
    op.drop_column('usuarios', 'localizacao')
    # ### end Alembic commands ###
