"""empty message

Revision ID: 93d1f6108a8b
Revises: 8e047386cb28
Create Date: 2020-10-06 14:07:24.490960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d1f6108a8b'
down_revision = '8e047386cb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('confirmado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'confirmado')
    # ### end Alembic commands ###
