"""empty message

Revision ID: c065f3d5d009
Revises: 443a859635b6
Create Date: 2022-01-22 00:06:24.828302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c065f3d5d009'
down_revision = '443a859635b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licoes_amei', sa.Column('licao_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'licoes_amei', type_='foreignkey')
    op.create_foreign_key(None, 'licoes_amei', 'licoes', ['licao_id'], ['id'])
    op.drop_column('licoes_amei', 'licoe_id')
    op.add_column('materias', sa.Column('nome_simples', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'materias', ['nome_simples'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materias', type_='unique')
    op.drop_column('materias', 'nome_simples')
    op.add_column('licoes_amei', sa.Column('licoe_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'licoes_amei', type_='foreignkey')
    op.create_foreign_key(None, 'licoes_amei', 'licoes', ['licoe_id'], ['id'])
    op.drop_column('licoes_amei', 'licao_id')
    op.add_column('emblemas', sa.Column('nome_foto', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
