"""empty message

Revision ID: cb011f79ff02
Revises: c065f3d5d009
Create Date: 2022-01-22 04:57:51.178515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb011f79ff02'
down_revision = 'c065f3d5d009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('descricao', sa.String(length=400), nullable=True))
    op.add_column('cursos', sa.Column('instrutor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cursos', 'usuarios', ['instrutor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cursos', type_='foreignkey')
    op.drop_column('cursos', 'instrutor_id')
    op.drop_column('cursos', 'descricao')
    # ### end Alembic commands ###
