"""empty message

Revision ID: cfb9eb6a86da
Revises: 5617d00232eb
Create Date: 2021-12-05 21:01:03.678852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb9eb6a86da'
down_revision = '5617d00232eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emblemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('nome_foto', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_emblemas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('emblema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emblema_id'], ['emblemas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'emblema_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_emblemas')
    op.drop_table('emblemas')
    # ### end Alembic commands ###
