"""empty message

Revision ID: d20a5fa7f48d
Revises: 
Create Date: 2021-01-13 16:11:21.700054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20a5fa7f48d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('padrao', sa.Boolean(), nullable=True),
    sa.Column('permissoes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_roles_padrao'), 'roles', ['padrao'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('nome_usuario', sa.String(length=25), nullable=True),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('sobrenome', sa.String(length=64), nullable=True),
    sa.Column('localizacao', sa.String(length=64), nullable=True),
    sa.Column('sobre', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=True),
    sa.Column('membro_desde', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_nome_usuario'), 'usuarios', ['nome_usuario'], unique=True)
    op.create_table('publicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('conteudo_html', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('idioma', sa.String(length=8), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicacoes_data'), 'publicacoes', ['data'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('conteudo_html', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('desativado', sa.Boolean(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('publicacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_data'), 'comentarios', ['data'], unique=False)
    op.create_table('publicacoes_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('publicacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacoes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'publicacao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicacoes_tags')
    op.drop_index(op.f('ix_comentarios_data'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_publicacoes_data'), table_name='publicacoes')
    op.drop_table('publicacoes')
    op.drop_index(op.f('ix_usuarios_nome_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tags')
    op.drop_index(op.f('ix_roles_padrao'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
