"""empty message

Revision ID: e0e608d5571e
Revises: 3e7533747c82
Create Date: 2021-12-04 03:37:14.642889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e608d5571e'
down_revision = '3e7533747c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicacoes', sa.Column('tipo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicacoes', 'tipo')
    # ### end Alembic commands ###
