"""empty message

Revision ID: e19d91a49e71
Revises: 69de54181473
Create Date: 2021-11-30 07:53:14.319923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19d91a49e71'
down_revision = '69de54181473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicacoes', sa.Column('nome_foto', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicacoes', 'nome_foto')
    # ### end Alembic commands ###
