"""empty message

Revision ID: e9334db55cdc
Revises: 48c4a4645013
Create Date: 2020-10-21 14:27:11.523704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9334db55cdc'
down_revision = '48c4a4645013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicacoes', sa.Column('conteudo_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicacoes', 'conteudo_html')
    # ### end Alembic commands ###
