"""empty message

Revision ID: ee7394dfec9a
Revises: cb011f79ff02
Create Date: 2022-01-22 14:00:05.775286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7394dfec9a'
down_revision = 'cb011f79ff02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topicos', sa.Column('descricao', sa.String(length=400), nullable=True))
    op.add_column('topicos', sa.Column('titulo', sa.String(length=150), nullable=True))
    op.drop_column('topicos', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topicos', sa.Column('nome', sa.VARCHAR(length=150), nullable=True))
    op.drop_column('topicos', 'titulo')
    op.drop_column('topicos', 'descricao')
    # ### end Alembic commands ###
